### PR TITLE
Disable Automatic brightness

### PR DESCRIPTION
**Pull request by adrian1234a**
J3 don´t have sersors for this

### CODE REVIEW

**Comment by djeman** [comment]
Yep not false but I think it's better to remove the overlay on this option to get the default setting.

And ... you have asked me to enable ambient display on cm14, why you do not enable it on cm13 ? :)

**Comment by adrian1234a** [comment]
I start to used this fuction now

**Comment by djeman** [comment]
Oops it's a pull for the cm14.
Ok I will try it fast, I forgot why I added this bad option ^^

**Comment by djeman** [comment]
Only for information, the overlay directory in the device tree is used to change default settings in java xml.
This is the default file => https://github.com/LineageOS/android_frameworks_base/blob/cm-14.1/core/res/res/values/config.xml

**Pull request merged**
